name: SuperPickaxe-Prototype
version: ${project.version}
main: net.thanachot.superPickaxePrototype.SuperPickaxePrototype
api-version: '1.21'
dependencies:
  - name: ShiroCore
    required: true
    load: BEFORE
