name: SuperPickaxe-Prototype
version: ${project.version}
main: net.thanachot.superPickaxePrototype.SuperPickaxePlugin
api-version: '1.21'
dependencies:
  server:
    ShiroCore:
      load: AFTER
      required: true
