name: SuperPickaxe-Prototype
version: ${project.version}
main: net.thanachot.superPickaxePrototype.SuperPickaxePlugin
api-version: '1.21'
dependencies:
  server:
    ShiroCore:
      load: BEFORE
      required: false
      version: '>=2.0.0'